#!/usr/bin/env python3
"""Version + release helper for OpenRx.

Single source of truth: the ``VERSION`` file at the repository root (semver).
``set`` also stamps that number into both ``package.json`` files and into
``backend/src/config/version.ts`` so it ships inside the compiled backend bundle
(the ``/config`` endpoint reports it, and the SPA reads it from there).

Subcommands
-----------
    current                      print the current version
    check <version>              validate semver + that the git tag is free
    set <version>                write the version everywhere
    bump major|minor|patch       bump the current version, then set it
    notes [--since <tag>] [--version <v>]
                                 markdown release notes from git history

The version can also be overridden at runtime with the ``APP_VERSION`` env var.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "VERSION"
BACKEND_PKG = ROOT / "backend/package.json"
FRONTEND_PKG = ROOT / "interface/new/package.json"
VERSION_TS = ROOT / "backend/src/config/version.ts"

SEMVER = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")


def _fail(msg: str) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)


def read_version() -> str:
    if not VERSION_FILE.exists():
        _fail(f"{VERSION_FILE} not found")
    v = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not SEMVER.match(v):
        _fail(f"VERSION file is not semver: {v!r}")
    return v


def _bump(v: str, part: str) -> str:
    core = v.split("-", 1)[0].split("+", 1)[0]
    major, minor, patch = (int(x) for x in core.split("."))
    if part == "major":
        major, minor, patch = major + 1, 0, 0
    elif part == "minor":
        minor, patch = minor + 1, 0
    elif part == "patch":
        patch += 1
    else:
        _fail(f"unknown bump part: {part}")
    return f"{major}.{minor}.{patch}"


def _tag_exists(tag: str) -> bool:
    try:
        out = subprocess.run(
            ["git", "tag", "-l", tag], cwd=ROOT, capture_output=True, text=True
        )
    except OSError:
        return False
    return bool(out.stdout.strip())


def _write_json_version(path: Path, version: str) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("version") == version:
        return
    data["version"] = version
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _write_version_ts(version: str) -> None:
    VERSION_TS.parent.mkdir(parents=True, exist_ok=True)
    VERSION_TS.write_text(
        "// Generated by tools/release.py — do not edit by hand.\n"
        "// Ships the version inside the compiled backend bundle; /config reports it.\n"
        f"export const APP_VERSION = '{version}';\n",
        encoding="utf-8",
    )


def set_version(version: str, *, make_tag: bool = False) -> None:
    if not SEMVER.match(version):
        _fail(f"not semver: {version!r}")
    VERSION_FILE.write_text(version + "\n", encoding="utf-8")
    _write_json_version(BACKEND_PKG, version)
    _write_json_version(FRONTEND_PKG, version)
    _write_version_ts(version)
    print(f"[release] version set to {version}")


def cmd_current(_args) -> int:
    print(read_version())
    return 0


def cmd_check(args) -> int:
    v = args.version
    if not SEMVER.match(v):
        _fail(f"not semver: {v!r}")
    if _tag_exists(f"v{v}"):
        _fail(f"tag v{v} already exists — pick a new version")
    print(f"[release] {v} is valid and tag v{v} is free")
    return 0


def cmd_set(args) -> int:
    set_version(args.version)
    return 0


def cmd_bump(args) -> int:
    set_version(_bump(read_version(), args.part))
    return 0


def cmd_notes(args) -> int:
    since = args.since
    if not since:
        try:
            out = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                cwd=ROOT, capture_output=True, text=True,
            )
            since = out.stdout.strip() or None
        except OSError:
            since = None
    rng = f"{since}..HEAD" if since else "HEAD"
    try:
        log = subprocess.run(
            ["git", "log", "--no-merges", "--pretty=format:%s", rng],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        _fail(f"git log failed: {exc}")
    title = args.version or read_version()
    lines = [f"# OpenRx {title}", ""]
    if since:
        lines += [f"Changes since {since}:", ""]
    commits = [c for c in log.splitlines() if c.strip()]
    lines += ([f"- {c}" for c in commits] or ["- (no changes)"])
    print("\n".join(lines))
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="OpenRx version + release helper.")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("current").set_defaults(func=cmd_current)

    s = sub.add_parser("check"); s.add_argument("version"); s.set_defaults(func=cmd_check)
    s = sub.add_parser("set"); s.add_argument("version"); s.set_defaults(func=cmd_set)
    s = sub.add_parser("bump")
    s.add_argument("part", choices=["major", "minor", "patch"])
    s.set_defaults(func=cmd_bump)

    s = sub.add_parser("notes")
    s.add_argument("--since", default="")
    s.add_argument("--version", default="")
    s.set_defaults(func=cmd_notes)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
