#!/usr/bin/env python3
"""Version + release helper for OpenRx.

Single source of truth: the ``VERSION`` file at the repository root (semver).
``set`` also stamps that number into both ``package.json`` files and into
``backend/src/config/version.ts`` so it ships inside the compiled backend bundle
(the ``/config`` endpoint reports it, and the SPA reads it from there).

Subcommands
-----------
    current                      print the current version
    check <version>              validate semver + that the git tag is free
    set <version>                write the version everywhere
    bump major|minor|patch       bump the current version, then set it
    notes [--since <tag>] [--version <v>]
                                 markdown release notes from git history

The version can also be overridden at runtime with the ``APP_VERSION`` env var.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "VERSION"
BACKEND_PKG = ROOT / "backend/package.json"
FRONTEND_PKG = ROOT / "interface/new/package.json"
VERSION_TS = ROOT / "backend/src/config/version.ts"

SEMVER = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$")


def _fail(msg: str) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)


def read_version() -> str:
    if not VERSION_FILE.exists():
        _fail(f"{VERSION_FILE} not found")
    v = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not SEMVER.match(v):
        _fail(f"VERSION file is not semver: {v!r}")
    return v


def _bump(v: str, part: str) -> str:
    core = v.split("-", 1)[0].split("+", 1)[0]
    major, minor, patch = (int(x) for x in core.split("."))
    if part == "major":
        major, minor, patch = major + 1, 0, 0
    elif part == "minor":
        minor, patch = minor + 1, 0
    elif part == "patch":
        patch += 1
    else:
        _fail(f"unknown bump part: {part}")
    return f"{major}.{minor}.{patch}"


def _tag_exists(tag: str) -> bool:
    try:
        out = subprocess.run(
            ["git", "tag", "-l", tag], cwd=ROOT, capture_output=True, text=True
        )
    except OSError:
        return False
    return bool(out.stdout.strip())


def _write_json_version(path: Path, version: str) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("version") == version:
        return
    data["version"] = version
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _write_version_ts(version: str) -> None:
    VERSION_TS.parent.mkdir(parents=True, exist_ok=True)
    VERSION_TS.write_text(
        "// Generated by tools/release.py — do not edit by hand.\n"
        "// Ships the version inside the compiled backend bundle; /config reports it.\n"
        f"export const APP_VERSION = '{version}';\n",
        encoding="utf-8",
    )


def set_version(version: str, *, make_tag: bool = False) -> None:
    if not SEMVER.match(version):
        _fail(f"not semver: {version!r}")
    VERSION_FILE.write_text(version + "\n", encoding="utf-8")
    _write_json_version(BACKEND_PKG, version)
    _write_json_version(FRONTEND_PKG, version)
    _write_version_ts(version)
    print(f"[release] version set to {version}")


def cmd_current(_args) -> int:
    print(read_version())
    return 0


def cmd_check(args) -> int:
    v = args.version
    if not SEMVER.match(v):
        _fail(f"not semver: {v!r}")
    if _tag_exists(f"v{v}"):
        _fail(f"tag v{v} already exists — pick a new version")
    print(f"[release] {v} is valid and tag v{v} is free")
    return 0


def cmd_set(args) -> int:
    set_version(args.version)
    return 0


def cmd_bump(args) -> int:
    set_version(_bump(read_version(), args.part))
    return 0


def cmd_notes(args) -> int:
    since = args.since
    if not since:
        try:
            out = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                cwd=ROOT, capture_output=True, text=True,
            )
            since = out.stdout.strip() or None
        except OSError:
            since = None
    rng = f"{since}..HEAD" if since else "HEAD"
    try:
        log = subprocess.run(
            ["git", "log", "--no-merges", "--pretty=format:%s", rng],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        _fail(f"git log failed: {exc}")
    title = args.version or read_version()
    lines = [f"# OpenRx {title}", ""]
    if since:
        lines += [f"Changes since {since}:", ""]
    commits = [c for c in log.splitlines() if c.strip()]
    lines += ([f"- {c}" for c in commits] or ["- (no changes)"])
    print("\n".join(lines))
    return 0


def _version_ts_value() -> str:
    text = VERSION_TS.read_text(encoding="utf-8")
    m = re.search(r"APP_VERSION\s*=\s*'([^']+)'", text)
    if not m:
        _fail(f"could not read APP_VERSION from {VERSION_TS.relative_to(ROOT)}")
    return m.group(1)


def _pkg_version(path: Path) -> str:
    return str(json.loads(path.read_text(encoding="utf-8")).get("version", ""))


def cmd_verify(args) -> int:
    """Consistency gate: every version source must equal the requested version."""
    want = args.version
    sources = {
        "VERSION": VERSION_FILE.read_text(encoding="utf-8").strip()
        if VERSION_FILE.exists() else "(missing)",
        "backend/package.json": _pkg_version(BACKEND_PKG),
        "interface/new/package.json": _pkg_version(FRONTEND_PKG),
        "backend/src/config/version.ts": _version_ts_value()
        if VERSION_TS.exists() else "(missing)",
    }
    mismatch = {k: v for k, v in sources.items() if v != want}
    if mismatch:
        print(f"error: version mismatch — expected {want!r}", file=sys.stderr)
        for k, v in sources.items():
            flag = "OK " if v == want else "BAD"
            print(f"  [{flag}] {k}: {v}", file=sys.stderr)
        raise SystemExit(1)
    print(f"[release] all version sources == {want}")
    return 0


def cmd_build_info(args) -> int:
    """Write BUILD_INFO.json — version + exact git commit + build time. No secrets."""
    import datetime as _dt

    def _git(*a: str) -> str:
        try:
            return subprocess.run(
                ["git", *a], cwd=ROOT, capture_output=True, text=True, check=True
            ).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            return ""

    info = {
        "version": args.version or read_version(),
        "gitCommit": _git("rev-parse", "HEAD"),
        "gitShortCommit": _git("rev-parse", "--short", "HEAD"),
        "buildTime": _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "backendVersion": _pkg_version(BACKEND_PKG),
        "frontendVersion": _pkg_version(FRONTEND_PKG),
    }
    text = json.dumps(info, indent=2) + "\n"
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"[release] wrote {args.out}")
    else:
        print(text, end="")
    return 0


def cmd_github_release(args) -> int:
    """Create/update a GitHub Release for a tag and upload assets.

    Uses the GitHub REST API via urllib (no extra tools). The token is read from
    the ``GITHUB_TOKEN`` (or ``GH_TOKEN``) env var and is never printed.
    Idempotent: if the release for the tag already exists it is reused.
    """
    import os
    import urllib.error
    import urllib.parse
    import urllib.request

    notes = ""
    if args.notes_file:
        notes = Path(args.notes_file).read_text(encoding="utf-8")

    if args.dry_run:
        print(f"[gh] DRY-RUN: would publish release '{args.name or args.tag}' "
              f"for tag {args.tag} on {args.repo}")
        print(f"[gh]   body: {len(notes)} chars; assets: {args.asset}")
        return 0

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        _fail("GITHUB_TOKEN (or GH_TOKEN) is not set")

    api = "https://api.github.com"

    def _req(method: str, url: str, data=None, ctype="application/json"):
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "openrx-release",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if ctype:
            headers["Content-Type"] = ctype
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode("utf-8") or "{}")

    payload = {
        "tag_name": args.tag,
        "name": args.name or args.tag,
        "body": notes,
        "draft": bool(args.draft),
        "prerelease": bool(args.prerelease),
    }
    try:
        rel = _req("POST", f"{api}/repos/{args.repo}/releases",
                   json.dumps(payload).encode())
    except urllib.error.HTTPError as exc:
        if exc.code == 422:  # already exists for this tag
            rel = _req("GET", f"{api}/repos/{args.repo}/releases/tags/"
                             f"{urllib.parse.quote(args.tag)}")
            print(f"[gh] release for {args.tag} already exists (id {rel.get('id')})")
        else:
            _fail(f"GitHub API {exc.code}: {exc.read().decode('utf-8', 'replace')[:300]}")

    rid = rel["id"]
    upload_url = rel["upload_url"].split("{", 1)[0]
    print(f"[gh] release {args.tag} -> {rel.get('html_url')}")

    for path in args.asset or []:
        p = Path(path)
        if not p.exists():
            print(f"[gh]   skip missing asset: {path}")
            continue
        data = p.read_bytes()
        url = f"{upload_url}?name={urllib.parse.quote(p.name)}"
        try:
            _req("POST", url, data, ctype="application/octet-stream")
            print(f"[gh]   uploaded {p.name} ({len(data)} bytes)")
        except urllib.error.HTTPError as exc:
            _fail(f"asset upload failed for {p.name}: {exc.code} "
                  f"{exc.read().decode('utf-8', 'replace')[:200]}")
    return 0


def cmd_smoke(args) -> int:
    """Post-deploy smoke test against a running deployment.

    Read-only. Verifies /config (appName + version), the SPA root + one referenced
    asset, authentication (login -> token), and key read-only routes. Exits
    non-zero if any check fails.
    """
    import ssl
    import urllib.error
    import urllib.request

    base = args.base_url.rstrip("/")
    ctx = ssl._create_unverified_context() if args.insecure else None
    failures: list[str] = []

    def _get(path: str, token=None):
        req = urllib.request.Request(base + path, method="GET")
        req.add_header("Accept", "application/json")
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        try:
            with urllib.request.urlopen(req, timeout=args.timeout, context=ctx) as r:
                return r.status, r.read()
        except urllib.error.HTTPError as exc:
            return exc.code, exc.read()
        except Exception as exc:  # noqa: BLE001 - report any transport error
            return 0, str(exc).encode()

    def check(name: str, ok: bool, detail: str = "") -> None:
        print(f"[smoke] {'OK  ' if ok else 'FAIL'} {name}" + (f"  ({detail})" if detail else ""))
        if not ok:
            failures.append(name)

    # 1. /config
    status, body = _get("/api/config")
    config = {}
    if status == 200:
        try:
            config = json.loads(body)
        except ValueError:
            config = {}
    check("GET /api/config -> 200", status == 200, f"status={status}")
    check("/config has appName", bool(config.get("appName")), f"appName={config.get('appName')!r}")
    if args.expected_version:
        check(f"/config version == {args.expected_version}",
              config.get("version") == args.expected_version,
              f"got {config.get('version')!r}")
    else:
        check("/config has version", bool(config.get("version")),
              f"version={config.get('version')!r}")

    # 2. SPA root + one referenced asset
    status, body = _get("/")
    html = body.decode("utf-8", "replace")
    check("GET / -> 200", status == 200, f"status={status}")
    check("SPA index mounts #root", 'id="root"' in html)
    asset = re.search(r"/assets/[A-Za-z0-9._/-]+", html)
    check("index.html references /assets/", bool(asset))
    if asset:
        astatus, _ = _get(asset.group(0))
        check(f"GET {asset.group(0)} -> 200", astatus == 200, f"status={astatus}")

    # 3. authentication + read-only routes
    token = None
    if args.user and args.password:
        req = urllib.request.Request(
            base + "/api/auth/login",
            data=json.dumps({"username": args.user, "password": args.password}).encode(),
            method="POST",
        )
        req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=args.timeout, context=ctx) as r:
                token = json.loads(r.read()).get("token")
            check("login returns a token", bool(token))
        except Exception as exc:  # noqa: BLE001
            check("login returns a token", False, str(exc)[:150])
    else:
        print("[smoke] login skipped (no --user/--password)")

    for route in args.route or ["/api/patients"]:
        rstatus, _ = _get(route, token=token)
        if token:
            check(f"GET {route} -> 200", rstatus == 200, f"status={rstatus}")
        else:
            check(f"GET {route} rejects anonymous", rstatus in (401, 403), f"status={rstatus}")

    if failures:
        print(f"[smoke] FAILED: {len(failures)} check(s): {', '.join(failures)}")
        return 1
    print("[smoke] all checks passed")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="OpenRx version + release helper.")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("current").set_defaults(func=cmd_current)

    s = sub.add_parser("check"); s.add_argument("version"); s.set_defaults(func=cmd_check)
    s = sub.add_parser("set"); s.add_argument("version"); s.set_defaults(func=cmd_set)
    s = sub.add_parser("bump")
    s.add_argument("part", choices=["major", "minor", "patch"])
    s.set_defaults(func=cmd_bump)

    s = sub.add_parser("notes")
    s.add_argument("--since", default="")
    s.add_argument("--version", default="")
    s.set_defaults(func=cmd_notes)

    s = sub.add_parser("verify")
    s.add_argument("version")
    s.set_defaults(func=cmd_verify)

    s = sub.add_parser("build-info")
    s.add_argument("--version", default="")
    s.add_argument("--out", default="")
    s.set_defaults(func=cmd_build_info)

    s = sub.add_parser("github-release")
    s.add_argument("--repo", required=True, help="owner/name")
    s.add_argument("--tag", required=True, help="e.g. v1.0.0")
    s.add_argument("--name", default="", help="release title (default: the tag)")
    s.add_argument("--notes-file", default="", help="markdown body")
    s.add_argument("--asset", action="append", default=[], help="file to upload (repeatable)")
    s.add_argument("--draft", action="store_true")
    s.add_argument("--prerelease", action="store_true")
    s.add_argument("--dry-run", action="store_true", help="print intent; do not call the API")
    s.set_defaults(func=cmd_github_release)

    s = sub.add_parser("smoke")
    s.add_argument("--base-url", required=True, help="deployment origin, e.g. https://openrx.example")
    s.add_argument("--expected-version", default="", help="fail unless /config reports this version")
    s.add_argument("--user", default="", help="login username (optional)")
    s.add_argument("--password", default="", help="login password (optional)")
    s.add_argument("--route", action="append", default=[], help="read-only route to check (repeatable)")
    s.add_argument("--timeout", type=int, default=20)
    s.add_argument("--insecure", action="store_true", help="skip TLS verification")
    s.set_defaults(func=cmd_smoke)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
